### 
POST {{local}}/addClientToServe
content-type: application/json

{
"clientPublicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/getNodeId
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/startSession
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
